# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SLWeiBo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SLWeiBo
  pod 'SVProgressHUD'
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'MJRefresh'
  # 当前开发环境swift版本2.2
  pod 'SnapKit', '~> 0.22.0'

  target 'SLWeiBoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SLWeiBoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
